# Generated by Django 3.0.3 on 2020-04-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentdetails',
            new_name='studentdetail',
        ),
    ]
